"""empty message

Revision ID: e6a0b49f2050
Revises: 78e36fbbe116
Create Date: 2022-03-05 16:20:13.696677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a0b49f2050'
down_revision = '78e36fbbe116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('changed_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('changed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'changed_on')
    op.drop_column('user', 'created_on')
    op.drop_column('task', 'changed_on')
    op.drop_column('task', 'created_on')
    # ### end Alembic commands ###
